// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQAsboXD9g1rrU-ysKpy8UP8X_RsZBSh8',
    appId: '1:694150940690:web:d905f9e48c8e78f1de30cb',
    messagingSenderId: '694150940690',
    projectId: 'flutter-test-app-b6e75',
    authDomain: 'flutter-test-app-b6e75.firebaseapp.com',
    storageBucket: 'flutter-test-app-b6e75.appspot.com',
    measurementId: 'G-J9YHLXJR87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjie2IZm5xhVSNlJclkr7Bne3oH8QteZk',
    appId: '1:694150940690:android:299bfaaa745a372dde30cb',
    messagingSenderId: '694150940690',
    projectId: 'flutter-test-app-b6e75',
    storageBucket: 'flutter-test-app-b6e75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGTvlkStbtlH2xFqHsPtGcEm2cLVU98KE',
    appId: '1:694150940690:ios:6fdaa4f061de82dbde30cb',
    messagingSenderId: '694150940690',
    projectId: 'flutter-test-app-b6e75',
    storageBucket: 'flutter-test-app-b6e75.appspot.com',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGTvlkStbtlH2xFqHsPtGcEm2cLVU98KE',
    appId: '1:694150940690:ios:6fdaa4f061de82dbde30cb',
    messagingSenderId: '694150940690',
    projectId: 'flutter-test-app-b6e75',
    storageBucket: 'flutter-test-app-b6e75.appspot.com',
    iosBundleId: 'com.example.flutterTestApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQAsboXD9g1rrU-ysKpy8UP8X_RsZBSh8',
    appId: '1:694150940690:web:05d905a468a5a64ade30cb',
    messagingSenderId: '694150940690',
    projectId: 'flutter-test-app-b6e75',
    authDomain: 'flutter-test-app-b6e75.firebaseapp.com',
    storageBucket: 'flutter-test-app-b6e75.appspot.com',
    measurementId: 'G-5XP415GLFR',
  );
}